### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by sjkelly** [JuliaCI/pkg.julialang.org#10]
A sitemap would help google results. 

We will need to make anchors on each package.

**Comment by sjkelly** [comment]
Anchors are started here: https://github.com/IainNZ/packages.julialang.org/pull/1

**Comment by IainNZ** [comment]
I'm not sure this page will ever be ranked high by Google, given its a single page site with 300+ outbound links. Pull requests welcome, this is a low priority

**Comment by sjkelly** [comment]
@IainNZ I will work on a PR. I have some of this work already done for my personal site.
