### ISSUE TITLE
List registered package without tagged version

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/pkg.julialang.org#12]
The discussion starts here: https://github.com/JuliaLang/METADATA.jl/pull/1316

It would be great to have packages in rolling release mode appearing on the search engine.

**Comment by IainNZ** [comment]
I'm not going to do this. If a package doesn't have a version, even a 0.0.1 version, it isn't ready to be used widely because there is no way to reproduce results/ensure stability in production.

**Comment by juliohm** [comment]
I don't understand, but anyways.

**Comment by IainNZ** [comment]
Let me try explaining a different way: people working on larger software projects need to be able to fix a package at a specific version. They can't have packages changing all the time during development. If a package has a version, you can pin it at that version and know it won't ever change. If a package is so unstable that it doesn't even have a version number, we don't think it should be showcased on the julialang.org website.

**Comment by juliohm** [comment]
Stability has nothing to do with a mere version tag and release points shouldn't be a requirement for every existing package in my opinion.

The intent in rolling release is to fix bugs as fast as possible and only ask the user to `Pkg.update()` to get a working copy. No need to update METADATA and wait merges.

**Comment by IainNZ** [comment]
The point is that I have have a version tag, I can trust that version tag will always be the same thing - its deterministic. If things can change every time I run Pkg.update, then its hard to rely on it. Some other languages take this idea even further, e.g. Python's `pip` will freeze a package at the version it is at when you install it, so it doesn't even have an update functionality. Anyway, its your choice how to distribute your code as you see fit. Semantic versioning makes tagging x.x.? versions easy and semantically clear, and other packages don't have much trouble with it.

**Comment by juliohm** [comment]
Thanks Iain, I'll tag my repository in the future.
