### ISSUE TITLE
Package ImageQuilting not listed on the website

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/pkg.julialang.org#13]
What it is missing for the package to be shown on pkg.julialang.org? I tagged a version on METADATA: https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/ImageQuilting

**Comment by IainNZ** [comment]
Its generated by PackageEvaluator nightly starting around 2am EST so will probably appear when I do the manual check and upload tomorrow around 11am EST

**Comment by juliohm** [comment]
Thank you @IainNZ.
