### ISSUE TITLE
Show percentage by testing status

### ISSUE THREAD

**Issue by waldyrious** [JuliaCI/pkg.julialang.org#14]
The testing status charts used to show both the absolute number and percentage of packages at each testing status. With the new graphs in the [Pulse](http://pkg.julialang.org/pulse.html) page, the percentages are gone, but now that only the latest datapoint is shown in the table, it makes even more sense to include the percentages (since the result won't become too crowded).

**Comment by IainNZ** [comment]
Indeed, I'll add this
