### ISSUE TITLE
Add live link to repo description and readme

### ISSUE THREAD

**Issue by waldyrious** [JuliaCI/pkg.julialang.org#2]
Both to make it more convenient to access (one-click), and to prevent people from trying to access it from http://packages.julialang.org/ which isn't live (yet?)

**Comment by IainNZ** [comment]
If you click the package name it takes you to the package?

**Comment by IainNZ** [comment]
Or do you mean something else?

**Comment by IainNZ** [comment]
(if you click the version it even takes you to the specific commit)

**Comment by waldyrious** [comment]
No, I mean in this very github repo. (Sorry, I realize I wasn't entirely clear before)

**Comment by IainNZ** [comment]
Ah, good point!
