### ISSUE TITLE
Make taglines searchable

### ISSUE THREAD

**Issue by dpsanders** [JuliaCI/pkg.julialang.org#21]
Since package names are going to become increasingly opaque, I suggest to make the package taglines searchable, as well as just the package names. E.g. the package `JWAS` should be findable by typing `gen` ("genetics").

**Comment by dpsanders** [comment]
Maybe it should even be possible to associate keywords (i.e., true tags) with packages when registering them.

**Comment by IainNZ** [comment]
Use browser search feature perhaps? I was planning on removing the name search box anyway

**Comment by dpsanders** [comment]
The filter funcionality is actually much neater than scrolling through the huge list with browser search.

**Comment by mkborregaard** [comment]
A good example for the usefulness of this is in this question: https://stackoverflow.com/questions/45616604/why-doesnt-julia-support-something-like-switch-case/45620246

The Match.jl package provides the requested switch-case functionality for Julia, but that is not apparent when searching. The only way to realize this is to know it. 

It is particularly important to be able to find packages that provide core functionality under the current emphasis on making core Julia more lean and putting core functionality in packages.
