### ISSUE TITLE
Question About Renaming Packages

### ISSUE THREAD

**Issue by andrewcooke** [JuliaCI/pkg.julialang.org#22]
Sorry, this isn't an issue, but I can't see a way to message you.

Can I simply rename a package once it has been registered?  If I rename the github repo and then rename any textual occurrences of the name (including git mv of file names), will the package itself be renamed?

The reason for asking is that I want to rename AutoHashEquals to DeriveHashEquals.

Also, is there a better way of contacting you?  Would it have been better to post in julia-users?  Sorry if so.

Thanks,
Andrew

**Comment by IainNZ** [comment]
This isn't an issue for me, this an issue for METADATA, which this just reflects.

Renaming issues is strongly discouraged, but if no one has installed it yet then it is possible to submit a PR for renaming it. The sooner the better - don't merge it yourself straight away though.

**Comment by IainNZ** [comment]
Feel free to post issues either here or the PackageEvaluator repository if the `pkg.julialang.org` is wrong.
