### ISSUE TITLE
Print VERSION in PkgEval logs

### ISSUE THREAD

**Issue by mbauman** [JuliaCI/pkg.julialang.org#23]
Is there a way to tell precisely which Julia `VERSION` a failing PkgEval log is from?  It'd be nice to have this information directly inline with the logs when trying to verify or reproduce a user's bug report.

Actually, perhaps this belongs in PkgEval… feel free to close/move/etc.

**Comment by IainNZ** [comment]
Ahh darn I lost this in a refactor. I'll get this in before tonights run at 1:30am

**Comment by mbauman** [comment]
Sweet.  Thanks!
