### ISSUE TITLE
Link to file issue with PackageEvaluator for developers

### ISSUE THREAD

**Issue by IainNZ** [JuliaCI/pkg.julialang.org#3]

**Comment by waldyrious** [comment]
Maybe link to issues page instead, as the issue may have already been submitted. I suggest adding this next to the "Show log" / "Show history" links (and perhaps not visible if status is "tests passing").

**Comment by IainNZ** [comment]
Now clicking on any of the links, e.g. to see the test log, will reveal a link to file an issue with PackageEvaluator. It otherwise remains invisible.
