### ISSUE TITLE
prefix AngularJS attributes with "data-"

### ISSUE THREAD

**Issue by waldyrious** [JuliaCI/pkg.julialang.org#6]
To make the document valid HTML5. See [here](http://stackoverflow.com/questions/12107504/angularjs-tags-attributes).

**Comment by IainNZ** [comment]
Pretty sure almost no one (not even Google) does this in production

**Comment by waldyrious** [comment]
That might be true, but given that [AngularJS natively supports it](http://docs.angularjs.org/guide/directive#matching-directives), is there any downside?
