### ISSUE TITLE
search README.md ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaCI/pkg.julialang.org#9]
the package descriptions are frequently redundant with the names, and sometimes neither are informative.  would it make sense / be easy to search the documentation too?

**Comment by WestleyArgentum** [comment]
This would be great!

**Comment by pwl** [comment]
+1 for this, at least there should be an option to search package description (many packages names don't reflect their functionality).  Do you want to solve a differential equation?  No luck, because searching for "differential" doesn't return any results.

**Comment by IainNZ** [comment]
You can search package descriptions right now - just use the search functionality in your browser.

As for searching READMEs, I don't think its as good an idea as you might think as many important packages don't use their READMEs like that, e.g. https://github.com/JuliaStats/DataFrames.jl

**Comment by pwl** [comment]
I didn't know it was intentional.  It would be cool if it worked like I described though, I suppose some people (including me) could be mislead this.  And then, why do you need the search function at all when you can find everything using a browser?

**Comment by IainNZ** [comment]
I'm thinking of removing the search by name too - it seems fairly redundant.
Theres a more general package discovery problem right now, and the solution isn't so much sorting as categorizing/tagging - theres been some discussion but no one has dedicated the time to getting it off the ground yet.
